version: "3.9"

services:

  # ======================
  # PostgreSQL
  # ======================
  db:
    image: postgres:16
    container_name: mapp_pg_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Clave1234
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  # ======================
  # Laravel - PHP
  # ======================
  backend:
    build:
      context: ./docker/php
    container_name: mapp_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    environment:
      - DB_HOST=db # Aseg√∫rate que esto coincida con tu .env
    depends_on:
      - db

  # ======================
  # Nginx
  # ======================
  nginx:
    image: nginx:alpine
    container_name: mapp_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  # ======================
  # React
  # ======================
  frontend:
    image: node:20
    container_name: mapp_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true
    depends_on:
      - nginx

volumes:
  dbdata: